INSERT INTO `bo2_vanilla_round_leaderboard` VALUES (1, 'DieRise', 'DDDDec', 0);
INSERT INTO `bo2_vanilla_round_leaderboard` VALUES (2, 'Buried', 'DDDDec', 0);
INSERT INTO `bo2_vanilla_round_leaderboard` VALUES (3, 'MobOfTheDead', 'DDDDec', 0);
INSERT INTO `bo2_vanilla_round_leaderboard` VALUES (4, 'Nuketown', 'DDDDec', 0);
INSERT INTO `bo2_vanilla_round_leaderboard` VALUES (5, 'Origins', 'DDDDec', 0);
INSERT INTO `bo2_vanilla_round_leaderboard` VALUES (6, 'Town', 'DDDDec', 2);
INSERT INTO `bo2_vanilla_round_leaderboard` VALUES (7, 'Farm', 'DDDDec', 0);
INSERT INTO `bo2_vanilla_round_leaderboard` VALUES (8, 'Tranzit', 'DDDDec', 0);
INSERT INTO `bo2_vanilla_round_leaderboard` VALUES (9, 'Depot', 'DDDDec', 0);
